BINANCE_BASE_URL = "https://fapi.binance.com"

BINANCE_LIMIT = 1000
BINANCE_FUNDING_LIMIT = 1000
BINANCE_FUNDING_INTERVAL_MS = 8 * 60 * 60 * 1000

BINANCE_TIMEOUT = 20
BINANCE_MAX_WORKERS = 3
BINANCE_RETRY_COUNT = 5
BINANCE_RETRY_SLEEP = 0.25
BINANCE_REQUEST_WEIGHT_LIMIT_PER_MINUTE = 2400
