ENABLE_FEATURE_CLIP = True
FEATURE_CLIP_LOWER_Q = 0.01
FEATURE_CLIP_UPPER_Q = 0.99
USE_SYMBOL_FEATURE = False

MANUAL_DISABLED_FEATURE_COLUMNS = [
    "return_1h_24",
    "return_4h_3",
    "distance_to_session_low_1h",
    "slope_acceleration_1h_12_24",
    "range_compression_1h",
    "hour_cos_1h",
    "relative_strength_vs_btc_24h",
    "return_4h_1",
    "distance_to_session_high_1h",
    "return_1h_12",
    "return_1h_6",
    "is_weekend_1h",
    "crowded_longs_score_1h",
    "crowded_shorts_score_1h",
    "linear_regression_slope_atr_1h_24",
    "distance_to_rolling_low_4h",
    "residual_return_24h",
    "delta_market_breadth_ema_fast_slow_1h",
    "high_vol_stress_indicator",
    "breakout_quality_4h",
    "counter_market_penalty_1h",
    "signal_x_high_vol_stress",
    "vol_regime_classification",
    "trend_efficiency_x_vol_stability",
    "signal_market_agreement_1h",
    "breakout_quality_4h_x_volume_ratio_1h",
    "premium_index_zscore_7d",
    "volume_zscore_1h",
    "shorts_overheated_1h",
    "trend_persistence_score_24",
    "volatility_acceleration_1h",
    "dollar_volume_zscore_1h",
    "premium_index_1h",
    "realized_vol_vs_ema",
    "ema_fast_slow_x_vol_of_vol",
    "trend_efficiency_24h_x_volatility_regime_change_1h",
    "market_pressure_x_vol_regime",
    "trend_efficiency_24h",
    "trend_persistence_score_12",
    "donchian_width_change_4h",
    "open_interest_zscore_7d",
    "beta_to_btc_24h",
    "ema_fast_slow_x_market_breadth_ema_fast_slow_1h",
    "market_breadth_ema_fast_slow_1h_zscore",
    "market_directional_pressure_1h",
    "market_dispersion_return_4h_3",
    "range_width_atr_1h_48",
    "volume_24h",
    "open_interest_change_pct_24h",
    "open_interest_change_pct_8h",
    "hour_sin_1h",
    "volume_ratio_1h",
    "longs_overheated_1h",
    "funding_rate_change_24h",
    "open_interest_funding_crowding_1h",
    "donchian_width_atr_4h",
    "ema_slope_acceleration_1h",
    "vol_ratio",
    "funding_rate_zscore_7d",
    "trend_alignment_1h_4h",
    "return_4h_7",
    "vol_of_vol_1h",
    "realized_vol_1h",
    "bollinger_bandwidth_atr_1h_20",
    "bollinger_percent_b_1h_20",
    "distance_to_rolling_high_4h",
    "volatility_regime_stability",
    "market_abs_avg_ema_slope_4h",
    "market_avg_ema_slope_4h",
    "market_breadth_pos_return_4h_14",
    "market_mean_return_4h_14",
    "cross_sectional_rank_4h",
    "zscore_vs_vwap_1h",
    "linear_regression_slope_atr_1h_12",
    "range_position_1h_48",
    "mean_reversion_pressure_1h",
]

FEATURE_PROFILES = {
    "all": "__all__",
    "empty": [],
    "base_only": [
        "realized_vol_1h",
        "ema_fast_slow",
        "return_1h_24",
        "linear_regression_slope_atr_1h_24",
        "trend_efficiency_24h",
        "atr_ratio_1h",
        "range_compression_1h",
        "price_position_1h",
        "relative_strength_vs_btc_24h",
        "residual_return_24h",
        "return_4h_3",
        "return_4h_14",
        "ema_slope_4h",
        "realized_vol_4h_returns_20",
        "market_breadth_pos_return_4h_3",
        "market_dispersion_return_4h_3",
        "zscore_vs_vwap_4h",
        "vol_ratio",
        "price_position_4h",
        "adx_4h",
    ],
}

FEATURE_BUILD_REQUEST = {
    "profile": "all",
    "include_features": [],
    "exclude_features": [],
    "exclude_blocks": [],
}

MCC_SIGN_BTC_WINDOW = 24
MCC_SIGN_BTC_MIN_PERIODS = None
RSI_LENGTH = 14
