TAKER_COM = 0.0004
SLIPPAGE = 0.0003
LEVERAGE = 1
RISK_PER_TRADE = 0.01

DIRECTIONAL_PROBA_THRESHOLD = 0.55
CONFIDENCE_THRESHOLD = 0.55
MIN_SIGNAL_GAP = 0.01
ALLOW_LONGS = True
ALLOW_SHORTS = True

BACKTEST_INITIAL_BALANCE = 100.0
BACKTEST_MAX_NEW_POSITIONS_PER_BAR = 1
BACKTEST_MAX_OPEN_POSITIONS = 1
BACKTEST_SL_COOLDOWN_BARS = 8
BACKTEST_MAX_SL_PER_DAY = 3
BACKTEST_REDUCE_RISK_AFTER_CONSECUTIVE_LOSSES = 2
BACKTEST_REDUCED_RISK_PER_TRADE = 0.005
