ACTIVE_EXPERIMENT = "hybrid_v1_labels_v2_train"
LABELING_PROFILE = "v1"
TRAINING_PROFILE = "v2"

SAMPLE_WEIGHT_HALF_LIFE_DAYS = 180.0
REGIME_AWARE_WEIGHTING = True
REGIME_RECENT_DAYS_BOOST = 60.0
REGIME_RECENT_BOOST_FACTOR = 1.5
REGIME_WEIGHT_STRENGTH = 0.18
REGIME_WEIGHT_STRENGTH_CAP = 0.25
REGIME_WEIGHT_SLOPE_SCALE_4H = 0.08
SAMPLE_WEIGHT_MIN = 0.8
SAMPLE_WEIGHT_MAX = 1.35

EARLY_STOPPING_ROUNDS = 200
UNSTABLE_FOLD_MIN_BEST_ITER = 25
UNSTABLE_FOLD_FALLBACK_MIN_ESTIMATORS = 150
UNSTABLE_FOLD_FALLBACK_DEFAULT_ESTIMATORS = 250
